import type { CollectionConfig } from 'payload'

export const Materials: CollectionConfig = {
  slug: 'materials',
  admin: {
    useAsTitle: 'name',
    defaultColumns: ['name', 'category', 'price', 'unit', 'inStock'],
    group: 'Content',
  },
  access: {
    read: () => true,
  },
  fields: [
    { name: 'name', type: 'text', required: true },
    { name: 'photo', type: 'upload', relationTo: 'media', required: false },
    {
      name: 'category',
      type: 'select',
      required: true,
       options: [
       { label: 'Bolts & Fasteners', value: 'bolts-fasteners' },
       { label: 'Steel Plates', value: 'steel-plates' },
       { label: 'Sheet Pile', value: 'sheet-pile' },
       { label: 'Steel Bars & Tubing', value: 'steel-bars' },
       { label: 'Beams', value: 'beams' },
       { label: 'Black Iron', value: 'black-iron' },
       { label: 'Galvanized Iron', value: 'galvanized-iron' },
       { label: 'Copper', value: 'copper' },
       { label: 'Stainless', value: 'stainless' },
       { label: 'Pipe Fittings', value: 'pipe-fittings' },
       { label: 'Fence & Wire', value: 'fence-wire' },
       { label: 'PPE', value: 'ppe' },
       { label: 'Electrical & Cabling', value: 'electrical-cabling' },
  ],
    },
    {
      name: 'unit',
      type: 'select',
      required: true,
      defaultValue: 'piece',
      options: [
        { label: 'per piece', value: 'piece' },
        { label: 'per bag', value: 'bag' },
        { label: 'per kg', value: 'kg' },
        { label: 'per sack', value: 'sack' },
        { label: 'per cubic meter', value: 'cbm' },
        { label: 'per sq. meter', value: 'sqm' },
        { label: 'per linear meter', value: 'lm' },
        { label: 'per length/bar', value: 'length' },
        { label: 'per set', value: 'set' },
      ],
    },
    { name: 'description', type: 'textarea' },
    { name: 'material', type: 'text'},
    { name: 'usage', type: 'text'},
    { name: 'inStock', type: 'checkbox', defaultValue: true, label: 'In stock / available' },
    { name: 'featured', type: 'checkbox', defaultValue: false, label: 'Show in homepage highlights' },
    {
      name: 'weightCalcProduct',
      type: 'relationship',
      relationTo: 'weight-calc-products',
      required: false,
      admin: { description: 'Optional: link a weight calculator shape/formula for this material\'s detail page' },
    },
  ],
}
